spring.application.name=fin-control-backend

# api-bank DB
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5436/fincontrol}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.hikari.maximum-pool-size=2

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# Configuracao do Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.default_schema=fin_control
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.default-schema=fin_control
spring.flyway.schemas=fin_control
spring.flyway.locations=classpath:db/migration

# JWT
api.security.token.secret=${JWT_SECRET:my_secret_key}
