-- =====================================================================
-- SCHEMA FINANCEIRO - PostgreSQL
-- =====================================================================

-- ---------------------------------------------------------------------
-- USERS
-- ---------------------------------------------------------------------
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(100) NOT NULL,
  email        VARCHAR(255),
  password_hash VARCHAR(255) NOT NULL,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMP NOT NULL DEFAULT now(),
  updated_at   TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email    UNIQUE (email)
);

-- ---------------------------------------------------------------------
-- PROFILES
-- ---------------------------------------------------------------------
CREATE TABLE profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  full_name   VARCHAR(255),
  display_name VARCHAR(100),
  birthdate   DATE,
  locale      VARCHAR(10),
  timezone    VARCHAR(64),
  currency    CHAR(3),
  phone       VARCHAR(30),
  avatar_url  TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_profiles_user UNIQUE (user_id),
  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Índice pra joins / buscas por usuário
CREATE INDEX idx_profiles_user ON profiles (user_id);

-- ---------------------------------------------------------------------
-- SESSIONS
-- ---------------------------------------------------------------------
CREATE TABLE sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  jti        VARCHAR(36) NOT NULL,       -- UUID em string (pode virar UUID depois)
  token_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  last_used_at TIMESTAMP,
  expires_at TIMESTAMP,
  ip         VARCHAR(45),
  user_agent TEXT,
  revoked    BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_sessions_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_sessions_user ON sessions (user_id);

-- ---------------------------------------------------------------------
-- ACCOUNTS
-- ---------------------------------------------------------------------
CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   BIGINT NOT NULL,
  name      VARCHAR(100) NOT NULL,
  type      VARCHAR(30),                 -- ex: CONTA_CORRENTE, CARTAO, etc.
  balance   DECIMAL(19,2) NOT NULL DEFAULT 0,
  currency  CHAR(3) NOT NULL DEFAULT 'BRL',
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_accounts_user_name UNIQUE (user_id, name),
  CONSTRAINT fk_accounts_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_accounts_user ON accounts (user_id);

-- ---------------------------------------------------------------------
-- CATEGORIES
-- ---------------------------------------------------------------------
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   BIGINT NOT NULL,
  name      VARCHAR(100) NOT NULL,
  parent_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_categories_user_name UNIQUE (user_id, name),
  CONSTRAINT fk_categories_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_categories_parent
    FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE INDEX idx_categories_user ON categories (user_id);

-- ---------------------------------------------------------------------
-- TAGS
-- ---------------------------------------------------------------------
CREATE TABLE tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   BIGINT NOT NULL,
  name      VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT uq_tags_user_name UNIQUE (user_id, name),
  CONSTRAINT fk_tags_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_tags_user ON tags (user_id);

-- ---------------------------------------------------------------------
-- TRANSACTIONS
-- ---------------------------------------------------------------------
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  account_id  BIGINT,
  category_id BIGINT,
  date        DATE NOT NULL,
  type        VARCHAR(20) NOT NULL,      -- ENTRADA / SAIDA (pode virar ENUM no futuro)
  description TEXT,
  amount      DECIMAL(19,2) NOT NULL,
  status      VARCHAR(20) NOT NULL,      -- PAGO / PENDENTE / AGENDADO (pode virar ENUM)
  is_installment   BOOLEAN NOT NULL DEFAULT FALSE,
  installment_total INT,
  installment_index INT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT fk_transactions_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_transactions_account
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_transactions_category
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Índices para relatórios e consultas frequentes
CREATE INDEX idx_transactions_user_date ON transactions (user_id, date);
CREATE INDEX idx_transactions_account   ON transactions (account_id);
CREATE INDEX idx_transactions_category  ON transactions (category_id);

-- ---------------------------------------------------------------------
-- TRANSACTION_TAGS (N:N)
-- ---------------------------------------------------------------------
CREATE TABLE transaction_tags (
  transaction_id BIGINT NOT NULL,
  tag_id         BIGINT NOT NULL,
  PRIMARY KEY (transaction_id, tag_id),
  CONSTRAINT fk_transaction_tags_tx
    FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
  CONSTRAINT fk_transaction_tags_tag
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

CREATE INDEX idx_transaction_tags_tx  ON transaction_tags (transaction_id);
CREATE INDEX idx_transaction_tags_tag ON transaction_tags (tag_id);

-- ---------------------------------------------------------------------
-- INVESTMENTS
-- ---------------------------------------------------------------------
CREATE TABLE investments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL,
  account_id BIGINT,
  name       VARCHAR(150) NOT NULL,
  type       VARCHAR(50),                -- CDB, TESOURO, ACOES, FII, etc.
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT fk_investments_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_investments_account
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET NULL
);

CREATE INDEX idx_investments_user ON investments (user_id);

-- ---------------------------------------------------------------------
-- INVESTMENT_MOVEMENTS
-- ---------------------------------------------------------------------
CREATE TABLE investment_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investment_id BIGINT NOT NULL,
  date          DATE NOT NULL,
  movement_type VARCHAR(20) NOT NULL,    -- APORTE / RESGATE / RENDIMENTO
  amount        DECIMAL(19,2) NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT fk_invest_mov_investment
    FOREIGN KEY (investment_id) REFERENCES investments(id) ON DELETE CASCADE
);

CREATE INDEX idx_invest_mov_investment ON investment_movements (investment_id);
CREATE INDEX idx_invest_mov_date       ON investment_movements (date);
